### ISSUE TITLE
Fails to start service 

### ISSUE THREAD

**Issue by huntergregal** [hugsy/gef-binja#3]
* Latest Binja (Version 2.0.2166 Personal (Build ID 1a310da0))

```
user:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```
```
[+] Starting service on 0.0.0.0:1337
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.binaryninja/repositories/community/plugins/hugsy_gefbinja/__init__.py", line 118, in start_service
    __gef_instance = Gef(server, bv)
  File "/home/user/.binaryninja/repositories/community/plugins/hugsy_gefbinja/gef.py", line 50, in __init__
    tag_type = bv.tag_types["Breakpoints"] if "Breakpoints" in bv.tag_types else Tag
NameError: name 'Tag' is not defined
```

**Comment by hugsy** [comment]
Thanks it is fixed on the GH. I'll issue a new release soon with other things that got fixed.
For a now (and a very quick fix), you can install the Vector35 debugger plugin, which is the one that defines the "Breakpoint" tag type.

Cheers,
